### ISSUE TITLE
How to limit log file size

### ISSUE THREAD

**Issue by GalayZloy** [CyrilKuzmin/any-json-to-metrics#1]
How to limit log file size? in 2 weeks it grows up to 130 mb...

**Comment by CyrilKuzmin** [comment]
It depends on your setup :) 
If you use docker just limit logs on its side by logging options `max-size` and/or `max-file`. For example: `docker run --log-opt max-size=10m --log-opt max-file=1 ...` (or apply the same options in yamls)
In case of systemd unit you can [configure a logging namespace](https://wiki.archlinux.org/title/Systemd/Journal#Per_unit_size_limit_by_a_journal_namespace) for the unit

**Comment by GalayZloy** [comment]
I'm not good at docker. I thought there is a setting for the application, as it is done in others, for example: log_level = warn/all/info

**Comment by CyrilKuzmin** [comment]
Indeed, I didn't bother about logging because of configuration on our infra side. 

But I'll add flags for logging soon

**Comment by GalayZloy** [comment]
Thank you! I will be waiting.
